// src-svelte-redesign/src/routes/projects/modcord/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fly } from 'svelte/transition';
  import SEO from '$lib/components/SEO.svelte';
  import GradientBackdrop from '$lib/components/GradientBackdrop.svelte';
  import { MODCORD_CONTENT } from '$lib/content';
  import { BACKGROUND_LAYERS, ICON_PATHS, EXTERNAL_LINKS } from '$lib/constants';
  import { GRADIENTS } from '$lib/styles';

  let visible = $state(false);

  const iconMap: Record<string, string> = {
    discord: ICON_PATHS.discord,
    github: ICON_PATHS.github,
  };

  onMount(() => {
    visible = true;
  });
</script>

<SEO title="ModCord | HoneyBerries" description={MODCORD_CONTENT.headerLead} pathname="/projects/modcord" />
<GradientBackdrop layers={BACKGROUND_LAYERS.modcord} />

{#if visible}
  <div class="relative z-10">
    <article class="max-w-6xl mx-auto px-4 py-12">
      <!-- Header -->
      <header class="text-center mb-16 max-w-4xl mx-auto" in:fly={{ y: 20, duration: 500 }}>
        <h1 class="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-gray-900 mb-6 leading-tight">
          Modcord: <span class="accent-text">Smart AI Moderation</span> for Your Discord Server
        </h1>
        <p class="text-xl text-gray-600 mb-8 leading-relaxed max-w-3xl mx-auto">{MODCORD_CONTENT.headerLead}</p>
        <div class="flex flex-col sm:flex-row gap-4 justify-center items-center">
          {#each MODCORD_CONTENT.heroButtons as btn}
            <a
              href={btn.href}
              target="_blank"
              rel="noopener noreferrer"
              class={btn.variant === 'primary'
                ? 'btn-primary rounded-lg whitespace-nowrap gap-2'
                : 'inline-flex items-center gap-2 px-6 py-3 rounded-lg border border-gray-300 text-gray-700 font-medium hover:bg-gray-50 transition-colors whitespace-nowrap'}
              style={btn.variant === 'primary' && btn.gradientKey ? `background: ${GRADIENTS[btn.gradientKey] ?? ''}` : ''}
            >
              {#if iconMap[btn.icon]}
                <img src={iconMap[btn.icon]} alt="" class="w-5 h-5" />
              {/if}
              {btn.label}
            </a>
          {/each}
        </div>
      </header>

      <!-- Features Section -->
      <section class="mb-12">
        <div class="text-center mb-12" in:fly={{ y: 20, duration: 500, delay: 80 }}>
          <h3 class="text-3xl font-bold text-gray-950 mb-2">Why Choose ModCord over Others?</h3>
        </div>

        <div class="grid sm:grid-cols-2 lg:grid-cols-2 gap-8">
          {#each MODCORD_CONTENT.features as feature, i}
            <div
              class="card-glass p-8 h-full bg-gradient-to-br {feature.gradient}"
              in:fly={{ y: 20, duration: 400, delay: 150 + i * 100 }}
            >
              <h3 class="text-xl font-bold text-gray-900 mb-3">{feature.title}</h3>
              <p class="text-gray-600 leading-relaxed">{feature.description}</p>
            </div>
          {/each}
        </div>
      </section>

      <!-- CTA Section -->
      <section class="text-center" in:fly={{ y: 30, duration: 500, delay: 300 }}>
        <div class="card-glass p-8 max-w-4xl mx-auto bg-gradient-to-r from-blue-50/50 to-purple-50/50">
          <h2 class="text-2xl font-bold text-gray-900 mb-4">{MODCORD_CONTENT.cta.heading}</h2>
          <p class="text-gray-600 mb-6 leading-relaxed">{MODCORD_CONTENT.cta.description}</p>
          <div class="flex flex-col sm:flex-row gap-4 justify-center">
            <a
              href={EXTERNAL_LINKS.modcordInvite}
              target="_blank"
              rel="noopener noreferrer"
              class="btn-primary"
              style="background: {GRADIENTS.emeraldBlueBright}"
            >
              Get Started
            </a>
            <a
              href="/contact"
              class="btn-primary"
              style="background: {GRADIENTS.orangePurple}"
            >
              Contact Us
            </a>
          </div>
        </div>
      </section>
    </article>
  </div>
{/if}

// src_busted/pages/projects/Modcord.jsx
import SEO from '../../components/SEO';
import { GradientBackdrop } from '../../components/backgrounds';
import { BACKGROUND_LAYERS, EXTERNAL_LINKS, ICON_PATHS } from '../../lib/constants';
import { MODCORD_CONTENT } from '../../lib/content';
import { gradientStyle } from '../../lib/styles';
import { Link } from 'react-router-dom';
import { Button } from '../../components/ui';
import { motion } from 'framer-motion';

/**
 * Modcord page - describes the AI moderation bot for Discord
 */
export default function Modcord() {
  return (
    <div className="min-h-screen relative">
      <SEO
        title="Modcord, AI Moderation Bot for Discord"
        description="Modcord uses AI to provide intelligent, context-aware moderation for Discord servers. Designed for privacy and scalability."
        ogImage="/assets/backgrounds/modcord-background.webp"
        pathname="/projects/modcord"
        jsonLd={{
          "@context": "https://schema.org",
          "@type": "BreadcrumbList",
          "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "Home", "item": "https://honeyberries.net/" },
            { "@type": "ListItem", "position": 2, "name": "Projects", "item": "https://honeyberries.net/projects" },
            { "@type": "ListItem", "position": 3, "name": "Modcord", "item": "https://honeyberries.net/projects/modcord" }
          ]
        }}
      />
      <GradientBackdrop layers={BACKGROUND_LAYERS.modcord} />
      
      <div className="relative z-10">
        <article className="max-w-6xl mx-auto px-4 py-12">
          <ModcordHeader />
          <FeaturesSection />
          <CallToActionSection />
        </article>
      </div>
    </div>
  );
}

/**
 * Hero header section with enhanced typography and styling
 */
function ModcordHeader() {
  return (
    <motion.header 
      className="text-center mb-16 max-w-4xl mx-auto"
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.2 }}
      transition={{ duration: 0.6 }}
    >
      <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-gray-900 mb-6 leading-tight">
        Modcord: <span className="accent-text">Smart AI Moderation</span> for Your Discord Server
      </h1>
      <p className="text-xl text-gray-600 mb-8 leading-relaxed max-w-3xl mx-auto">
        {MODCORD_CONTENT.headerLead}
      </p>
      
      <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
        {MODCORD_CONTENT.heroButtons.map((btn) => (
          <Button
            key={btn.label}
            as="a"
            href={btn.href}
            target="_blank"
            rel="noopener noreferrer"
            variant={btn.variant}
            className="rounded-lg whitespace-nowrap gap-2"
            style={btn.gradientKey ? gradientStyle(btn.gradientKey) : undefined}
          >
            {btn.icon === 'discord' && (
              <img
                src={ICON_PATHS.discord}
                alt="Discord"
                className="w-5 h-5"
              />
            )}
            {btn.icon === 'github' && (
              <img
                src={ICON_PATHS.github}
                alt="GitHub"
                className="w-5 h-5"
              />
            )}
            {btn.label}
          </Button>
        ))}
      </div>
    </motion.header>
  );
}

/**
 * Enhanced features section with better visual hierarchy
 */
function FeaturesSection() {
  return (
    <motion.section 
      className="mb-12"
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.2 }}
      transition={{ duration: 0.6 }}
    >
      <div className="text-center mb-12">
        <h3 className="text-3xl font-bold text-gray-950 mb-2">Why Choose ModCord over Others?</h3>
      </div>
      
      <div className="grid sm:grid-cols-2 lg:grid-cols-2 gap-8">
        {MODCORD_CONTENT.features.map((feature, index) => (
          <motion.div
            key={feature.title}
            className={`card-glass p-8 h-full bg-linear-to-br ${feature.gradient}`}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.2 }}
            transition={{ duration: 0.5, delay: index * 0.12 }}
            whileHover={{ 
              y: -8,
              boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)'
            }}
          >
            <h3 className="text-xl font-bold text-gray-900 mb-3">{feature.title}</h3>
            <p className="text-gray-600 leading-relaxed">{feature.description}</p>
          </motion.div>
        ))}
      </div>
    </motion.section>
  );
}

/**
 * Call to action section with privacy note
 */
function CallToActionSection() {
  return (
    <motion.section 
      className="text-center"
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.2 }}
      transition={{ duration: 0.6 }}
    >
      <div className="card-glass p-8 max-w-4xl mx-auto bg-linear-to-r from-blue-50/50 to-purple-50/50">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">{MODCORD_CONTENT.cta.heading}</h2>
        <p className="text-gray-600 mb-6 leading-relaxed">
          {MODCORD_CONTENT.cta.description}
        </p>
        <div className="flex flex-col sm:flex-row gap-4 justify-center">
          <Button
            as="a"
            href={EXTERNAL_LINKS.modcordInvite}
            target="_blank"
            rel="noopener noreferrer"
            variant="primary"
            style={gradientStyle('emeraldBlueBright')}
          >
            Get Started
          </Button>
          <Button
            as={Link}
            to="/contact"
            variant="primary"
            style={gradientStyle('orangePurple')}
          >
            Contact Us
          </Button>
        </div>
      </div>
    </motion.section>
  );
}
