// components/site/footer.tsx
import Link from "next/link"

import { SITE_NAME } from "@/lib/data/site"

export function Footer() {
  return (
    <footer className="border-t py-8">
      <div className="mx-auto flex max-w-5xl flex-wrap items-center justify-between gap-x-6 gap-y-3 px-6 text-sm text-muted-foreground">
        <span>© 2026 {SITE_NAME}</span>
        <nav aria-label="Modcord legal" className="flex gap-4">
          <Link
            href="/projects/modcord/privacy"
            className="underline-offset-4 hover:text-foreground hover:underline"
          >
            Modcord privacy
          </Link>
          <Link
            href="/projects/modcord/terms"
            className="underline-offset-4 hover:text-foreground hover:underline"
          >
            Modcord terms
          </Link>
        </nav>
        <span className="font-medium">honeyberries.net</span>
      </div>
    </footer>
  )
}

// src-svelte-redesign/src/lib/components/Footer.svelte
<script lang="ts">
  import { SITE_INFO } from '$lib/constants';
</script>

<footer class="border-t border-gray-200/60 mt-auto">
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 py-8 text-center">
    <p class="text-sm text-gray-500">
      &copy; {SITE_INFO.currentYear} {SITE_INFO.author}. All rights reserved.
    </p>
    <div class="mt-2 flex justify-center gap-4 text-xs text-gray-400">
      <a href="/projects/modcord/privacy-policy" class="hover:text-gray-600 transition-colors">Privacy Policy</a>
      <a href="/projects/modcord/terms-of-service" class="hover:text-gray-600 transition-colors">Terms of Service</a>
    </div>
  </div>
</footer>
