// src/components/Navbar.jsx
import { Link, NavLink } from 'react-router-dom'
import { useState } from 'react'
import { navLinks, projects } from '../data'

const navLinkClass = ({ isActive }) =>
  `px-3 py-2 text-sm font-medium rounded-md transition-colors ${
    isActive ? 'text-blue-700' : 'text-gray-700 hover:text-gray-900'
  }`

export default function Navbar() {
  const [open, setOpen] = useState(false)

  return (
    <header className="fixed top-0 inset-x-0 z-50 bg-white/80 backdrop-blur border-b border-gray-200">
      <div className="max-w-6xl mx-auto px-4">
        <div className="flex items-center justify-between h-16">
          <Link to="/" className="flex items-center gap-2">
            <span className="w-2.5 h-2.5 rounded-full bg-emerald-500 animate-pulse"></span>
            <span className="font-semibold tracking-tight">HoneyBerries</span>
          </Link>

          {/* Desktop nav */}
          <nav className="hidden md:flex items-center gap-1">
            {navLinks.map((link) => {
              if (link.name === 'Projects') {
                return (
                  <div key={link.name} className="relative group">
                    <NavLink to={link.path} className={navLinkClass}>{link.name}</NavLink>
                    <div className="invisible opacity-0 group-hover:visible group-hover:opacity-100 transition-all duration-200 absolute left-0 mt-2 w-56 bg-white shadow-xl border border-gray-200 rounded-lg p-2">
                      {projects.map((project) => (
                        <Link key={project.id} to={`/projects#${project.id}`} className="flex items-center gap-2 px-3 py-2 rounded-md text-sm text-gray-700 hover:bg-gray-50">
                          {project.title}
                        </Link>
                      ))}
                    </div>
                  </div>
                )
              }
              return (
                <NavLink key={link.name} to={link.path} className={navLinkClass}>
                  {link.name}
                </NavLink>
              )
            })}
          </nav>

          {/* Mobile menu button */}
          <button onClick={() => setOpen(v => !v)} className="md:hidden inline-flex items-center justify-center rounded-md p-2 text-gray-700 hover:bg-gray-100">
            <span className="sr-only">Open menu</span>
            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" className="w-6 h-6">
              {open ? (
                <path fillRule="evenodd" d="M5.47 5.47a.75.75 0 011.06 0L12 10.94l5.47-5.47a.75.75 0 111.06 1.06L13.06 12l5.47 5.47a.75.75 0 11-1.06 1.06L12 13.06l-5.47 5.47a.75.75 0 11-1.06-1.06L10.94 12 5.47 6.53a.75.75 0 010-1.06z" clipRule="evenodd" />
              ) : (
                <path fillRule="evenodd" d="M3.75 6.75a.75.75 0 000 1.5h16.5a.75.75 0 000-1.5H3.75zm0 4.5a.75.75 0 000 1.5h16.5a.75.75 0 000-1.5H3.75zm0 4.5a.75.75 0 000 1.5h16.5a.75.75 0 000-1.5H3.75z" clipRule="evenodd" />
              )}
            </svg>
          </button>
        </div>

        {/* Mobile nav */}
        {open && (
          <div className="md:hidden pb-3 animate-floatIn">
            <nav className="flex flex-col gap-1 border-t border-gray-200 pt-2">
              {navLinks.map((link) => (
                <div key={link.name}>
                  <NavLink onClick={() => setOpen(false)} to={link.path} className={navLinkClass}>
                    {link.name}
                  </NavLink>
                  {link.name === 'Projects' && (
                    <div className="pl-3">
                      {projects.map((project) => (
                        <Link key={project.id} onClick={() => setOpen(false)} to={`/projects#${project.id}`} className="block px-3 py-1.5 text-sm text-gray-600">
                          • {project.title}
                        </Link>
                      ))}
                    </div>
                  )}
                </div>
              ))}
            </nav>
          </div>
        )}
      </div>
    </header>
  )
}

// src-svelte-redesign/src/lib/components/Navbar.svelte
<script lang="ts">
  import { page } from '$app/state';
  import { slide, fade } from 'svelte/transition';
  import { NAV_LINKS } from '$lib/constants';

  let mobileOpen = $state(false);

  function isActive(path: string): boolean {
    if (path === '/') return page.url.pathname === '/';
    return page.url.pathname.startsWith(path);
  }

  function closeMobile() {
    mobileOpen = false;
  }
</script>

<nav class="fixed top-0 left-0 right-0 z-50 bg-white/80 backdrop-blur-md border-b border-gray-200/60">
  <div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 h-16 flex items-center justify-between">
    <!-- Logo -->
    <a href="/" class="flex items-center gap-2">
      <span class="text-lg font-bold text-gray-900">HoneyBerries</span>
      <span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span>
    </a>

    <!-- Desktop nav -->
    <div class="hidden md:flex items-center gap-1">
      {#each NAV_LINKS as link}
        <a
          href={link.path}
          class="px-3 py-2 text-sm font-medium rounded-md transition-colors {isActive(link.path)
            ? 'text-blue-700'
            : 'text-gray-700 hover:text-gray-900'}"
        >
          {link.name}
        </a>
      {/each}
    </div>

    <!-- Mobile menu button -->
    <button
      class="md:hidden p-2 rounded-md text-gray-700 hover:text-gray-900 transition-colors"
      onclick={() => (mobileOpen = !mobileOpen)}
      aria-label="Toggle menu"
    >
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
        {#if mobileOpen}
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
        {:else}
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        {/if}
      </svg>
    </button>
  </div>

  <!-- Mobile menu -->
  {#if mobileOpen}
    <!-- Overlay -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div
      class="fixed inset-0 top-16 z-40"
      transition:fade={{ duration: 200 }}
      onclick={closeMobile}
      onkeydown={(e) => { if (e.key === 'Escape') closeMobile(); }}
    ></div>

    <!-- Menu -->
    <div
      class="md:hidden bg-white/95 backdrop-blur-lg border-b border-gray-200/60 p-4"
      transition:slide={{ duration: 300 }}
    >
      <div class="flex flex-col gap-1">
        {#each NAV_LINKS as link}
          <a
            href={link.path}
            class="px-3 py-2 text-sm font-medium rounded-md transition-colors {isActive(link.path)
              ? 'text-blue-700'
              : 'text-gray-700 hover:text-gray-900'}"
            onclick={closeMobile}
          >
            {link.name}
          </a>
        {/each}
      </div>
    </div>
  {/if}
</nav>
