// src-svelte-redesign/src/routes/about/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { fly, fade } from 'svelte/transition';
  import SEO from '$lib/components/SEO.svelte';
  import GradientBackdrop from '$lib/components/GradientBackdrop.svelte';
  import { ABOUT_CONTENT } from '$lib/content';
  import { TIMELINE, CURRENT_PROJECTS } from '$lib/data';
  import { BACKGROUND_LAYERS } from '$lib/constants';

  let visible = $state(false);

  onMount(() => {
    visible = true;
  });
</script>

<SEO title="About | HoneyBerries" description={ABOUT_CONTENT.introLead} pathname="/about" />
<GradientBackdrop layers={BACKGROUND_LAYERS.about} />

{#if visible}
  <!-- Intro Section -->
  <section class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-16 pb-12">
    <div class="text-center mb-16">
      <div in:fly={{ y: 20, duration: 500 }}>
        <span class="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-100/80 border border-emerald-200 mb-6">
          <span class="relative flex h-2 w-2">
            <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
            <span class="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
          </span>
          <span class="text-sm font-medium text-emerald-700">{ABOUT_CONTENT.badgeLabel}</span>
        </span>
      </div>

      <h1
        class="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-gray-900 mb-6"
        in:fly={{ y: 20, duration: 500, delay: 100 }}
      >
        {ABOUT_CONTENT.introTitle}
      </h1>

      <p
        class="text-xl text-gray-600 mb-6 max-w-3xl mx-auto"
        in:fly={{ y: 20, duration: 500, delay: 200 }}
      >
        {ABOUT_CONTENT.introLead}
      </p>

      <p
        class="text-gray-500 max-w-2xl mx-auto"
        in:fly={{ y: 20, duration: 500, delay: 300 }}
      >
        {ABOUT_CONTENT.introBody}
      </p>
    </div>
  </section>

  <!-- Stats Grid -->
  <section class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-16">
    <div class="grid grid-cols-2 sm:grid-cols-4 gap-6">
      {#each ABOUT_CONTENT.stats as stat, i}
        <div
          class="card-glass p-5 text-center"
          in:fly={{ y: 20, duration: 500, delay: 400 + i * 80 }}
        >
          <div class="text-2xl mb-1">{stat.icon}</div>
          <div class="text-2xl font-bold {stat.color}">{stat.value}</div>
          <div class="text-xs text-gray-500 mt-1">{stat.label}</div>
        </div>
      {/each}
    </div>
  </section>

  <!-- Skills Section -->
  <section class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-16">
    <h2
      class="text-3xl font-bold text-gray-900 text-center mb-8"
      in:fade={{ duration: 400, delay: 500 }}
    >
      Skills & Technologies
    </h2>
    <div class="grid md:grid-cols-3 gap-6">
      {#each ABOUT_CONTENT.skillCategories as category, i}
        <div
          class="card-lift p-6"
          in:fly={{ y: 20, duration: 500, delay: 500 + i * 100 }}
        >
          <div class="w-12 h-12 bg-gradient-to-r {category.color} rounded-xl flex items-center justify-center mb-4">
            <span class="text-white font-bold text-lg">{category.title.charAt(0)}</span>
          </div>
          <h3 class="text-xl font-bold text-gray-900 mb-4">{category.title}</h3>
          <div class="flex flex-wrap gap-2">
            {#each category.skills as skill}
              <span class="px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-sm font-medium">
                {skill}
              </span>
            {/each}
          </div>
        </div>
      {/each}
    </div>
  </section>

  <!-- Timeline Section -->
  <section class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-16">
    <h2
      class="text-3xl font-bold text-gray-900 text-center mb-8"
      in:fade={{ duration: 400, delay: 600 }}
    >
      My Journey
    </h2>

    <div class="relative">
      <!-- Vertical line -->
      <div class="absolute left-8 top-0 bottom-0 w-0.5 bg-gradient-to-b from-emerald-500 to-blue-500"></div>

      <div class="space-y-8">
        {#each TIMELINE as entry, i}
          <div
            class="relative card-lift p-6 ml-16"
            in:fly={{ x: -20, duration: 500, delay: 650 + i * 120 }}
          >
            <!-- Dot -->
            <div class="absolute -left-20 top-6 w-4 h-4 bg-gradient-to-r from-emerald-500 to-blue-500 rounded-full border-4 border-white"></div>

            <div class="flex items-start justify-between gap-4 mb-3">
              <h3 class="text-xl font-bold text-gray-900">{entry.title}</h3>
              <span class="px-3 py-1 bg-emerald-100 text-emerald-700 rounded-full text-sm shrink-0">{entry.time}</span>
            </div>
            <p class="text-gray-600 leading-relaxed">
              {#if entry.hasLink && entry.linkUrl && entry.linkText}
                {@const parts = entry.desc.split(entry.linkText)}
                {parts[0]}<a href={entry.linkUrl} class="text-emerald-600 hover:underline" target="_blank" rel="noopener noreferrer">{entry.linkText}</a>{parts[1] ?? ''}
              {:else}
                {entry.desc}
              {/if}
            </p>
          </div>
        {/each}
      </div>
    </div>
  </section>

  <!-- Current Projects -->
  <section class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-12">
    <h2
      class="text-3xl font-bold text-gray-900 text-center mb-8"
      in:fade={{ duration: 400, delay: 800 }}
    >
      What I'm Working On
    </h2>
    <div class="grid sm:grid-cols-2 gap-6">
      {#each CURRENT_PROJECTS as project, i}
        <div
          class="card-lift p-6 h-full"
          in:fly={{ y: 20, duration: 500, delay: 800 + i * 80 }}
        >
          <div class="flex items-start gap-3">
            <span class="relative flex h-2 w-2 mt-2">
              <span class="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
              <span class="relative inline-flex rounded-full h-2 w-2 bg-emerald-500"></span>
            </span>
            <p class="text-gray-700 leading-relaxed flex-1">{project}</p>
          </div>
        </div>
      {/each}
    </div>
  </section>

  <!-- CTA Section -->
  <section class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pb-16 lg:pb-24">
    <div
      class="mt-12 text-center"
      in:fade={{ duration: 500, delay: 900 }}
    >
      <p class="text-gray-600 mb-6">{ABOUT_CONTENT.cta.message}</p>
      <a href={ABOUT_CONTENT.cta.buttonTo} class="btn-primary">
        {ABOUT_CONTENT.cta.buttonLabel}
      </a>
    </div>
  </section>
{/if}

// src_busted/pages/About.jsx
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import { Card, StatsGrid, Button } from '../components/ui';
import { GradientBackdrop } from '../components/backgrounds';
import { TIMELINE, CURRENT_PROJECTS } from '../lib/data';
import { BACKGROUND_LAYERS } from '../lib/constants';
import { ABOUT_CONTENT } from '../lib/content';
import { gradientStyle } from '../lib/styles';
import SEO from '../components/SEO';
import { pulse } from '../lib/animations';

/**
 * Enhanced About page component with modern design
 */
export default function About() {
  return (
    <div className="min-h-screen relative">
      <SEO
        title="About Me"
        description="Learn more about HoneyBerries, a developer passionate about building sleek, performant web apps, Minecraft plugins, and AI bots."
        ogImage="/assets/backgrounds/home-banner.webp"
        pathname="/about"
      />
      <GradientBackdrop layers={BACKGROUND_LAYERS.about} />

      <main className="relative z-10 max-w-4xl mx-auto px-4 py-16" role="main">
        <AboutHeader />
        <AboutStats />
        <SkillsSection />
        <Timeline />
        <CurrentProjects />
      </main>
    </div>
  );
}

/**
 * Enhanced about page header with better introduction
 */
function AboutHeader() {
  return (
    <motion.div 
      className="text-center mb-16"
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.2 }}
      transition={{ duration: 0.6 }}
    >
      <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-100/80 border border-emerald-200 mb-6">
        <motion.span className="w-2 h-2 rounded-full bg-emerald-500" {...pulse()} />
        <span className="text-sm font-medium text-emerald-700">{ABOUT_CONTENT.badgeLabel}</span>
      </div>
      <h1 className="text-4xl sm:text-5xl lg:text-6xl font-extrabold text-gray-900 mb-6 leading-tight">
        {ABOUT_CONTENT.introTitle.replace("HoneyBerries", '')}
        <span className="accent-text">HoneyBerries</span>
      </h1>
      <p className="text-xl text-gray-600 mb-6 max-w-3xl mx-auto leading-relaxed">
        {ABOUT_CONTENT.introLead}
      </p>
      <p className="text-gray-500 max-w-2xl mx-auto">
        {ABOUT_CONTENT.introBody}
      </p>
    </motion.div>
  );
}

/**
 * Quick stats about experience and projects
 */
function AboutStats() {
  return (
    <motion.div 
      className="mb-16"
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.2 }}
      transition={{ duration: 0.6, delay: 0.2 }}
    >
      <StatsGrid
        items={ABOUT_CONTENT.stats}
        animationStart={0.2}
        animationStep={0.1}
      />
    </motion.div>
  );
}

/**
 * Skills and technologies section
 */
function SkillsSection() {
  return (
    <motion.div 
      className="mb-16"
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.2 }}
      transition={{ duration: 0.6 }}
    >
      <h2 className="text-3xl font-bold text-gray-900 text-center mb-8">Skills & Technologies</h2>
      <div className="grid md:grid-cols-3 gap-6">
        {ABOUT_CONTENT.skillCategories.map((category, index) => (
          <motion.div 
            key={category.title}
            className="card-lift p-6"
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.2 }}
            transition={{ duration: 0.5, delay: index * 0.1 }}
          >
            <div className={`w-12 h-12 bg-linear-to-r ${category.color} rounded-xl flex items-center justify-center mb-4 shadow-lg`}>
              <span className="text-white font-bold text-lg">
                {category.title.charAt(0)}
              </span>
            </div>
            <h3 className="text-xl font-bold text-gray-900 mb-4">{category.title}</h3>
            <div className="flex flex-wrap gap-2">
              {category.skills.map(skill => (
                <span 
                  key={skill}
                  className="px-3 py-1 bg-gray-100 text-gray-700 rounded-full text-sm font-medium hover:bg-gray-200 transition-colors"
                >
                  {skill}
                </span>
              ))}
            </div>
          </motion.div>
        ))}
      </div>
    </motion.div>
  );
}

/**
 * Enhanced timeline section with better visual design
 */
function Timeline() {
  return (
    <motion.div 
      className="mb-16"
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.2 }}
      transition={{ duration: 0.6 }}
    >
      <h2 className="text-3xl font-bold text-gray-900 text-center mb-8">My Journey</h2>
      <div className="relative">
        {/* Timeline line */}
        <div className="absolute left-8 top-0 bottom-0 w-0.5 bg-linear-to-b from-emerald-500 to-blue-500"></div>
        
        <div className="space-y-8">
          {TIMELINE.map((item, index) => (
            <TimelineItem key={item.title} item={item} index={index} />
          ))}
        </div>
      </div>
    </motion.div>
  );
}

/**
 * Enhanced timeline item component with modern styling
 */
function TimelineItem({ item, index }) {
  const description = item.hasLink ? (
    <>
      {item.desc.split(item.linkText)[0]}
      {item.linkUrl && item.linkUrl.startsWith('/') ? (
        <Link to={item.linkUrl} className="text-emerald-600 hover:text-emerald-700 font-medium hover:underline transition-colors">{item.linkText}</Link>
      ) : (
        <a href={item.linkUrl} target="_blank" rel="noopener noreferrer" className="text-emerald-600 hover:text-emerald-700 font-medium hover:underline transition-colors">{item.linkText}</a>
      )}
      {item.desc.split(item.linkText)[1]}
    </>
  ) : item.desc;

  return (
    <motion.div 
      className="relative card-lift p-6 ml-16"
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.2 }}
      transition={{ duration: 0.5, delay: index * 0.1 }}
    >
      {/* Timeline dot */}
      <div className="absolute -left-20 top-6 w-4 h-4 bg-linear-to-r from-emerald-500 to-blue-500 rounded-full border-4 border-white shadow-lg"></div>
      
      <div className="flex items-start justify-between gap-4 mb-3">
        <h3 className="text-xl font-bold text-gray-900">{item.title}</h3>
        <span className="px-3 py-1 bg-emerald-100 text-emerald-700 rounded-full text-sm font-medium whitespace-nowrap">
          {item.time}
        </span>
      </div>
      <p className="text-gray-600 leading-relaxed">{description}</p>
    </motion.div>
  );
}

/**
 * Enhanced current projects section
 */
function CurrentProjects() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 30 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, amount: 0.2 }}
      transition={{ duration: 0.6 }}
    >
      <h2 className="text-3xl font-bold text-gray-900 text-center mb-8">What I'm Working On</h2>
      <div className="grid sm:grid-cols-2 gap-6">
        {CURRENT_PROJECTS.map((project, index) => (
          <motion.div 
            key={project}
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, amount: 0.2 }}
            transition={{ duration: 0.5, delay: index * 0.1 }}
          >
            <Card className="card-lift p-6">
              <div className="flex items-start gap-3">
                <motion.div 
                  className="w-2 h-2 rounded-full bg-emerald-500 mt-2 flex-shrink-0"
                  whileHover={{ scale: 1.25 }}
                  transition={{ duration: 0.3 }}
                />
                <p className="text-gray-700 leading-relaxed flex-1">
                  {project}
                </p>
              </div>
            </Card>
          </motion.div>
        ))}
      </div>
      
      {/* Call to action */}
      <div className="mt-12 text-center">
        <p className="text-gray-600 mb-6">
          {ABOUT_CONTENT.cta.message}
        </p>
        <Button
          as={Link}
          to={ABOUT_CONTENT.cta.buttonTo}
          variant="primary"
          style={gradientStyle(ABOUT_CONTENT.cta.gradientKey)}
        >
          <span>{ABOUT_CONTENT.cta.buttonLabel}</span>
          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 7l5 5m0 0l-5 5m5-5H6" />
          </svg>
        </Button>
      </div>
    </motion.div>
  );
}
